matchHigher: true 				# MatchParameters with teams above us
matchLower: false
kingslayerRank: 0
matchHigherNinetyDay: true		# Must have higher 90 day and lower normal
matchLowerNinetyDay: false
maxGames: 8 					# Maximum games for kingslayer
maxDiff: 50
mustMatch: 
playerPending:
  - 9maxmut9
playerNotPending:
  - 
teamOnly:
teamPending:
#  - ALCHEMY
#  - All Stars Honoured
#  - A Castle on the KING's Court # 2 // not good match ups
#  - Canadian Bacon
#  - Chess Galaxy
#  - Christ Our Redeemer
#  - Cowboys and Cowgirls of the Old West
#  - DACII LIBERI
#  - Dark Affair
#  - The Fighting Warriors
  - The Force
#  - IHS TEAM ITALIA
#  - Immortal Kings
#  - INTRPIDUS
#  - The Irish Pride
#  - Italians Do It Better
#  - Kings of the Castle
#  - Knightmare
#  - The Knights of the Crystal Castle
#  - Knights of the Sceptered Isle # too lopsided
  - KNIGHTS TEMPLAR
#  - LUCIFER'S ARMY
#  - Masters of the game
#  - Never Look Back                # 28/05/20 Cant match Kimcote
  - Peace, Love, and Bunny Rabbits # 27/05/20 cant match 
#  - Phoenix of the Kings Immortal
#  - Placida 
#  - Planet Chess
#  - Romania
#  - Salt and Light
#  - SmAsHeDcRaBs
#  - STONEDHENGE TRIBE
#  - S.W.A.T.
  - TRITON
#  - Underdogs
#  - The White Knight
#  - Yeshua's Army